# Generated by Django 2.2.7 on 2019-11-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('offer_text', models.CharField(max_length=255)),
                ('publication_date', models.CharField(max_length=40)),
            ],
        ),
    ]
