# Generated by Django 2.2.7 on 2019-11-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='offer',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
